config/routes.rb
Dawning::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: "home#index"

  get '/login', to: 'sessions#new', as: :login
  post '/authenticate', to: 'sessions#create', as: :authenticate
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/register', to: 'users#new', as: :register
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  resources :password_resets, except: [:index, :destroy]

  resources :users do
    get :activate, on: :member
  end

  resources :levels, only: :index do
    member do
      patch :join
      patch :continue
      delete :leave
    end
    resource :map, only: [:show]
    resource :dungeon, only: [:show]
  end

  namespace :admin do
    resource :launch_panel, only: [:show]
    resource :test_map, only: [:show, :update]
    namespace :api do
      namespace :v1 do
        resources :config_files, defaults: {format: 'json'}, only: [:index]
        resources :levels, defaults: {format: 'json'}, only: [:index, :show, :create, :destroy] do
          member do
            put :join
            put :build
            put :run
            put :stop
            get :objects_count
            post :terminal_command
          end
        end
      end
    end
  end
end

app/views/shared/_alert.html.haml
- if flash.any?
  .row.alert-box
    .col-md-12
      - flash.each do |name, message|
        .alert.alert-dismissable{:class => (name == 'notice' ? 'alert-success' : 'alert-danger')}
          %button.close{"type" => "button", "data-dismiss" => "alert", "aria-hidden" => "true"} &times
          - if name == 'notice'
            %i.fa.fa-info-circle
          - else
            %i.fa.fa-exclamation-circle
          = message

app/views/shared/_footer.html.haml
.footer
  .row
    .col-sm-8
      .row
        .col-md-6.social
          = link_to('https://github.com/grrrisu/dawning', :target => '_blank') do
            = image_tag('github.png', :size => '40x40', :class => 'icon')
            Github
        .col-md-6.social
          = link_to('http://lost-in-code.blogspot.com', :target => '_blank') do
            = image_tag('blog.png', :size => '40x40', :class => 'icon', :target => '_blank')
            Blog
      .row
        .col-md-6.social
          = link_to('http://twitter.com/#!/grrrisu', :target => '_blank') do
            = image_tag('twitter.png', :size => '40x40', :class => 'icon', :target => '_blank')
            Twitter
        .col-md-6.social
          = link_to('#', :target => '_blank') do
            = image_tag('rss.png', :size => '40x40', :class => 'icon', :target => '_blank')
            RSS Feed
    .col-sm-4{:style => 'text-align: right'}
      = link_to "About", "#"
      %br
      %br
      Copyright &copy; 2014 by
      = link_to "M42", "http://www.m42.ch", :target => "_blank"

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-static-top.navbar-inverse{role: 'navigation'}
  .nav-header
    %button.navbar-toggle{"type" => "button", "data-toggle" => "collapse", "data-target" => "#main-menu"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar

  #main-menu.navbar-collapse.collapse
    %ul.nav.navbar-nav
      = navigation_item 'Home', :home, root_path
      = navigation_item 'Documentation', :documentation, root_path
      = navigation_item 'User Ranking', :user_ranking, users_path
      - unless current_user
        = navigation_item 'Register', :register, register_path, id: 'register'
        = navigation_item 'Login', :login, login_path, id: 'login'
      - else
        = navigation_item 'Account', :account, edit_user_path(current_user)
        = navigation_item 'Levels', :levels, levels_path
        - if current_user.admin?
          %li.dropdown{class: subnavigation_active?(:admin) && 'active'}
            = link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
              Admin
              %b.caret
            %ul.dropdown-menu
              = navigation_item 'Launch Panel', [:admin, :launch_panel], admin_launch_panel_path, data: {:'no-turbolink' => true}
              = navigation_item 'Test Map', [:admin, :test_map], admin_test_map_path, data: {:'no-turbolink' => true}

    -if current_user
      .navbar-text.navbar-right
        = link_to 'Logout', logout_path, id: 'logout', class: 'navbar-link'