config/routes.rb
Dawning::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: "home#index"

  get '/login', to: 'sessions#new', as: :login
  post '/authenticate', to: 'sessions#create', as: :authenticate
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/register', to: 'users#new', as: :register
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  resources :password_resets, except: [:index, :destroy]

  resources :users do
    get :activate, on: :member
  end

  resources :levels, only: :index do
    member do
      patch :join
      patch :continue
      delete :leave
    end
    resource :map, only: [:show]
    resource :dungeon, only: [:show]
  end

  namespace :admin do
    resource :launch_panel, only: [:show]
    resource :test_map, only: [:show, :update]
    namespace :api do
      namespace :v1 do
        resources :config_files, defaults: {format: 'json'}, only: [:index]
        resources :levels, defaults: {format: 'json'}, only: [:index, :show, :create, :destroy] do
          member do
            put :join
            put :build
            put :run
            put :stop
            get :objects_count
            post :terminal_command
          end
        end
      end
    end
  end
end

app/controllers/admin/api/v1/levels_controller.rb
class Admin::Api::V1::LevelsController < ApplicationController

  authorize_resource

  before_filter :find_level, only: [:show, :run, :build, :join, :stop, :destroy, :objects_count, :terminal_command]

  respond_to :json

  def index
    data = LevelManager.instance.levels.map(&:as_json)
    respond_with data
  end

  def show
    render json: @level.as_json
  end

  def create
    level = LevelManager.instance.create params[:level][:name]
    render json: level.as_json
  end

  def build
    @level.build params[:level][:config]
    render json: @level.as_json
  end

  def run
    @level.start
    render json: @level.as_json
  end

  def stop
    @level.stop
    render json: @level.as_json
  end

  def destroy
    @level.remove
    render json: nil
  end

  def join
    @level.add_player current_user, role: :admin unless @level.find_player(current_user.id)
    render json: {success: true}
  end

  def objects_count
    render json: @level.objects_count
  end

  def terminal_command
    render json: {answer: @level.terminal_command(params[:command])}
  end

private

  def find_level
    unless @level = LevelManager.instance.find(params[:id])
      render json: {error: "Level with id #{params[:id]} not found"}, status: 404
    end
  end

end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  navigation :levels

  before_filter :find_level, only: [:join, :continue, :leave]

  def index
    authorize! :index, LevelProxy
    @levels = LevelManager.instance.actives
  end

  def join
    authorize! :join, @level
    @level.add_player current_user
    redirect_to levels_path
  end

  def continue

  end

  def leave
    @level.remove_player current_user.id
  end

private

  def find_level
    @level =  LevelManager.instance.find params[:id]
    redirect_to levels_path unless @level
  end

end

app/helpers/admin/levels_helper.rb
module Admin::LevelsHelper

  def level_configuration_files
    config_files = Dir.glob(Rails.root.join('config', 'levels', '*.yml'))
    config_files.map {|config_file| config_file.split('/').last }
  end

end

app/views/levels/index.html.haml
%legend
  Levels
- if @levels.any?
  .levels.row
    %ul.list-unstyled
      - @levels.each do |level|
        %li.col-md-3.col-sm-6
          .level{id: "level_#{level.id}", class: level.find_player(current_user.id) ? 'participation' : 'no-participation'}
            %h4= level.name.titleize
            %i.fa.fa-globe.fa-5x
            %br
            = level.state
            %br
            players:
            = level.players.size
            %br
            %br
            - unless player_id = level.find_player(current_user.id)
              = link_to join_level_path(level.id), method: :patch, class: 'btn btn-wide btn-primary', id: "join_#{level.id}" do
                %i.fa.fa-user
                %i.fa.fa-arrow-right
                Join
            - else
              = link_to level_dungeon_path(level.id), class: 'btn btn-wide btn-warning', id: "dungeon_#{level.id}", data: {'no-turbolink' => true} do
                %i.fa.fa-th
                Dungeon
              - if level.state == :running
                = link_to level_map_path(level.id), class: 'btn btn-wide btn-warning', id: "enter_#{level.id}", data: {'no-turbolink' => true} do
                  %i.fa.fa-sign-in
                  Enter
- else
  No levels available